name: Unit Tests

on:
  workflow_dispatch:
  

permissions:
  contents: read

defaults:
  run:
    shell: bash -el {0}

jobs:
  ubuntu:
    runs-on: ubuntu-22.04
    timeout-minutes: 90
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Extra installs
      run: sudo apt-get update && sudo apt-get install -y ${{ matrix.extra_apt }}

    - name: Generate extra locales
      # These extra locales will be available for locale.setlocale() calls in tests
      run: sudo locale-gen ${{ matrix.extra_loc }}

    - name: Set up Conda
      uses: ./.github/actions/setup-conda
      with:
        environment-file: ci/deps/${{ matrix.env_file }}

    - name: Build Pandas
      id: build
      uses: ./.github/actions/build_pandas
      with:
        meson_args: ${{ matrix.meson_args }}
        cflags_adds: ${{ matrix.cflags_adds }}

    - name: Test (not single_cpu)
      uses: ./.github/actions/run-tests
      with:
        preload: ${{ matrix.preload }}
        asan_options: ${{ matrix.asan_options }}
      env:
        # Set pattern to not single_cpu if not already set
        PATTERN: ${{ env.PATTERN == '' && 'not single_cpu' || matrix.pattern }}
